language: c
compiler:
  - gcc
#  - clang # broken, segv on loading modules
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libapr1 libapr1-dev flex libpcre3 libpcre3-dev sqlite3 libsqlite3-dev libsqlite3-0 libyaml-0-2 libyaml-dev libyaml-syck-perl perl-base libperl5.14 libperl-dev rubygems ruby-ffi 
  - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
  - git clone git://github.com/yahoo/mdbm.git mdbm
  - sh -c "cd mdbm; make; sudo make install PREFIX=/usr; cd /usr/lib; sudo ln ../lib64/libmdbm.so.4"
  - sudo dpkg --get-selections | grep -v deinstall
#  - sudo apt-get remove pip || true
  - sudo apt-get install python-pip python-dev build-essential
#  - sudo pip install --upgrade pip 
  - sudo pip list -o
  - sudo pip install cffi
script: cd source && ./doit.sh && ./testit.sh


notifications:
  irc:
    - "irc.freenode.net#range"
